### ISSUE TITLE
[1.16.3] Bows and tools cannot gain XP

### ISSUE THREAD

**Issue by Rukia1727** [TheMarstonConnell/randomlootmod#59] opened 2020-10-10 21:10 UTC
One person has stated bows and armor without fortiifed cannot gain XP, I'm not gaining XP using a bow.  The command says that the item is not a random loot item despite it being dropped by a loot box

**Comment by xLufi** [comment] 2020-11-05 01:36
I'm not gaining XP on any bows or armor, but other items are okay. I cannot edit XP on any of the random loot items, even the ones that do gain XP (swords/tools.)

Deleting the config file doesn't help. I've tried reinstalling the mod. I tried a fresh install+world with only Optifine, JEI, and Random Loot Mod. The issue is still present.

**Comment by TheMarstonConnell** [comment] 2021-02-16 03:25
Fixed in 2.1.8 and will be fixed in 2.1.9 hold tight!

**Closed by TheMarstonConnell** 2021-02-16 03:25 UTC
